import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navabar from "./navbar";
import Footer from "./(components)/footer";

const poppins = Poppins ({
  weight: ["100","200","300","400","500","600","700","800","900"],
  fallback: ["latin"],
  subsets: ["latin"]
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}
      >
        <Navabar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
