import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navabar from "./navbar";
import Footer from "./(components)/footer";

// 👇 Configured properly with subset
// const poppins = Poppins({
//   subsets: ['latin'],
//   weight: [
//     "100", "200", "300", "400", "500", "600", "700", "800", "900"
//   ],
//   preload: false,
//   variable: '--font-poppins',
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ${poppins.className} 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Navabar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
